### PR TITLE
Replace api token placeholders in JSON config

### PR DESCRIPTION
**Pull request by mbrcknl**
I'm aware that https://github.com/caddy-dns/cloudflare/pull/10 was previously declined, but hopefully this is closer to the way Caddy configuration is intended to work.

I don't yet fully understand what I'm doing here, but would be interested in any initial feedback and/or pointers. In particular, I'm still getting my head around the module/config lifecycle, and how to adequately test something like this.

My main goal here is to support placeholders in the JSON config for the API token. Placeholders are supported by similar config items like the ZeroSSL API key, so I'm assuming that's a reasonable thing to want. Prior to this change, I could only successfully authenticate to the Cloudflare API by writing my actual API token directly into my JSON config. (My JSON config, or rather the YAML from which it is adapted, is big enough that it wants to be in `git`, but I'd prefer to keep credentials out of `git`.) The first commit *appears* to achieve what I wanted, and I've not *yet* seen any adverse side effects, but I'll reserve judgement until I understand things better. :-)

I've noticed that autosaved JSON configs, as well as configs retrieved via the API include only the original placeholder, not its resolved value, so I guess the `Provision` call only happens on a copy of the JSON config? This is one of the aspects of the module/config lifecycle that I'm still trying to understand.

The second commit came from the observation that the replacements performed by the Caddyfile unmarshalling were likely made redundant by the replacements performed in the first commit. As a side effect of the observation in the previous paragraph, this seems to achieve what @hoshsadiq wanted in https://github.com/caddy-dns/cloudflare/pull/10. That is, if the Caddyfile (or JSON config for that matter) used a placeholder in the API token config, that placeholder is preserved in any JSON config that is autosaved or exported through the API, so the actual API token is hidden.

The third commit is just a dependency bump to the recently released Caddy 2.3.0. I'm happy to remove that if it doesn't belong here.

I'll mark this as draft while I continue tracing through the config/module lifecycle code, but would be grateful for any feedback you have in the meantime.

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Thanks for the thoughtful PR -- this appears to be correct.

Provisioning happens after JSON is unmarshaled, and is called to finish setting up the module before it is used.

To make sure that `Provision` stays intact and enforce that by the compiler, it's a good idea to add an "interface guard", a simple pattern that forces the compiler to throw an error if we mess up the Provision method signature: https://caddyserver.com/docs/extending-caddy#interface-guards

This is acceptable as-is, but if you have a moment to add the interface guard to the bottom of the file, that'd be good!

**Comment by mholt** [comment]
Thanks, when you're ready for a final review just un-draft it.

**Comment by mbrcknl** [comment]
Thanks for the reminder about the include guard. I had read the section you linked, but forgot about it. Amazingly, though, I had failed to read some other sections on that page, which would have answered my questions about the module lifecycle!

In particular, I now understand that the actual JSON config for the provider is stored in the [`ProviderRaw` field of `DNSChallengeConfig`](https://github.com/caddyserver/caddy/blob/b1bec8c8992424b423db3d92101bd5b4989dcf65/modules/caddytls/automation.go#L306). The `Provision` call doesn't touch that, so the original JSON config is preserved for autosaving and API export. The actual `Provision` call happens during [`LoadModule` in the `Provision` call on the `ACMEIssuer`](https://github.com/caddyserver/caddy/blob/b1bec8c8992424b423db3d92101bd5b4989dcf65/modules/caddytls/acmeissuer.go#L112), and the result ends up in the [`DNSProvider` field of a `certmagic.DNS01Solver`](https://github.com/caddyserver/caddy/blob/b1bec8c8992424b423db3d92101bd5b4989dcf65/modules/caddytls/acmeissuer.go#L127).

I think I also understand how the Caddyfile unmarshalling works. The call to `UnmarshalCaddyfile` happens in a couple of places, since there are two contexts in which the `dns` provider can be specified in a Caddyfile. For example, one of them is [inside an `issuer`](https://github.com/caddyserver/caddy/blob/b1bec8c8992424b423db3d92101bd5b4989dcf65/modules/caddytls/acmeissuer.go#L357-L368). The main point here is that the unmarshalling fills in the `DNS.ProviderRaw` field noted above, so all this happens before the JSON decoding above. So that's why it's not necessary to do the replacement here if we're going to do it in the `Provision` call.

Thanks, this has been quite educational! I'll squash that update into the relevant commit, then un-draft this...

**Comment by mholt** [comment]
Somebody did their homework!! Yes, that's all exactly correct.

I hope you will contribute again in the future. :) It's always great when members of the community learn from contributing, I'm pretty sure you're ahead of 99% of users in your understanding of your web server just because of that.

**Pull request merged**
