### PR TITLE
tidy mods

### LINKED ISSUE #69: Fatal error build with windows using master with latest release
`xcaddy build master --with github.com/caddy-dns/cloudflare`

```
2023/12/20 13:35:27 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe get -d -v github.com/caddy-dns/cloudflare github.com/caddyserver/caddy/v2@master
go: github.com/caddy-dns/cloudflare@v0.0.0-20231217194038-7b8ded472344 requires
        github.com/caddyserver/caddy/v2@v2.7.6, but v2.7.6-0.20231218231151-1bf72db6ff65 is requested
go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20231217194038-7b8ded472344) requires github.com/caddyserver/caddy/v2@v2.7.6, not github.com/caddyserver/caddy/v2@master (v2.7.6-0.20231218231151-1bf72db6ff65)
2023/12/20 13:35:27 [FATAL] exit status 1
```

https://i.imgur.com/1iOWgtn.png

### PR DESCRIPTION
**Pull request by mohammed90**
Fixes #69

### CODE REVIEW

**Comment by wazerstar** [comment]
Thanks !

**Comment by mohammed90** [comment]
> Thanks !
> 
> Still does it however
> 
> ```
> 2023/12/20 19:22:15 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe get -d -v github.com/caddy-dns/cloudflare github.com/caddyserver/caddy/v2@master
> go: github.com/caddy-dns/cloudflare@v0.0.0-20231220181002-8789126791ed requires
>         github.com/caddyserver/caddy/v2@v2.7.6, but v2.7.6-0.20231220153721-f976c84d9e5b is requested
> go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20231220181002-8789126791ed) requires github.com/caddyserver/caddy/v2@v2.7.6, not github.com/caddyserver/caddy/v2@master (v2.7.6-0.20231220153721-f976c84d9e5b)
> 2023/12/20 19:22:15 [FATAL] exit status 1
> ```
> 
> @mholt
> 
> @mohammed90

Huh, it worked when I tried it before shooting the PR. I can reproduce it now on a mac. Gotta think about it. I don't have a clue from the top of my head.

**Comment by mholt** [comment]
Works for me. Maybe your go cache needs to know about the latest commit? try @master on the caddy-dns package.

**Comment by wazerstar** [comment]
> Works for me. Maybe your go cache needs to know about the latest commit? try @master on the caddy-dns package.

Nope the same, also it downloads before doing its build I think so cannot be cache issue.

```
2023/12/20 20:07:14 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe get -d -v github.com/caddy-dns/cloudflare@master github.com/caddyserver/caddy/v2@master
go: github.com/caddy-dns/cloudflare@v0.0.0-20231220181002-8789126791ed requires
        github.com/caddyserver/caddy/v2@v2.7.6, but v2.7.6-0.20231220153721-f976c84d9e5b is requested
go: github.com/caddy-dns/cloudflare@master (v0.0.0-20231220181002-8789126791ed) requires github.com/caddyserver/caddy/v2@v2.7.6, not github.com/caddyserver/caddy/v2@master (v2.7.6-0.20231220153721-f976c84d9e5b)
2023/12/20 20:07:14 [FATAL] exit status 1
```

**Comment by wazerstar** [comment]
@mohammed90 are we still into this issue?

**Comment by mholt** [comment]
Mohammed's linked PR has the correct explanation; also from bcmills in the Gopher slack:

> Yes, this is because the v2.7.6 tag is on a release branch. Since [github.com/caddyserver/caddy/v2@master](http://github.com/caddyserver/caddy/v2@master) does not descend from v2.7.6, the go command doesn't know that it should be considered semantically higher than v2.7.6. You can fix that by adding a pre-release tag on the master branch, like [v2.8.0-0.dev](http://v2.8.0-0.dev/), which will then be used as the basis for pseudo-versions for the commits on that branch.

We're reconsidering our branching approach because I don't love this (personally).

**Comment by wazerstar** [comment]
> Mohammed's linked PR has the correct explanation; also from bcmills in the Gopher slack:
> 
> > Yes, this is because the v2.7.6 tag is on a release branch. Since [github.com/caddyserver/caddy/v2@master](https://github.com/caddyserver/caddy/v2@master) does not descend from v2.7.6, the go command doesn't know that it should be considered semantically higher than v2.7.6. You can fix that by adding a pre-release tag on the master branch, like [v2.8.0-0.dev](http://v2.8.0-0.dev/), which will then be used as the basis for pseudo-versions for the commits on that branch.
> 
> We're reconsidering our branching approach because I don't love this (personally).

Can you give me an example for how I would build the latest master as today, tried various method to add a prelease tag, never succeed.

I use this atm.

xcaddy build master --with github.com/caddy-dns/cloudflare --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation

**Comment by mohammed90** [comment]
Try this:

```
xcaddy build master --with github.com/caddy-dns/cloudflare=github.com/mohammed90/cloudflare --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation
```

**Comment by wazerstar** [comment]
> Try this:
> 
> ```
> xcaddy build master --with github.com/caddy-dns/cloudflare=github.com/mohammed90/cloudflare --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation
> ```

Hi, thanks for taking time, however gives another error now.

```
-replace=github.com/caddy-dns/cloudflare=github.com/mohammed90/cloudflare: unversioned new path must be local directory
2024/01/28 13:38:14 [FATAL] exit status 1
```

**Comment by mohammed90** [comment]
> > Try this:
> > ```
> > xcaddy build master --with github.com/caddy-dns/cloudflare=github.com/mohammed90/cloudflare --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation
> > ```
> 
> Hi, thanks for taking time, however gives another error now.
> 
> ```
> -replace=github.com/caddy-dns/cloudflare=github.com/mohammed90/cloudflare: unversioned new path must be local directory
> 2024/01/28 13:38:14 [FATAL] exit status 1
> ```

Sigh, sorry, my bad. This one works:

```
xcaddy build master --with github.com/caddy-dns/cloudflare@master=github.com/mohammed90/cloudflare@master --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation
```

This time, I checked it myself my creating a custom build using the same command.

**Comment by wazerstar** [comment]
> xcaddy build master --with github.com/caddy-dns/cloudflare@master=github.com/mohammed90/cloudflare@master --with github.com/caddyserver/transform-encoder --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/porech/caddy-maxmind-geolocation

Great it works, thanks! 👍 👍

**Pull request merged**
